export { default as Home } from "./home/home";
export { default as SinglePlayerGame } from "./single-player-game/single-player-game";
export { default as Settings } from "./settings/settings";
export { default as Login } from "./login/login";
export { default as SignUp } from "./signup/signup";
export { default as ChangePassword } from "./change-password/change-password";
export { default as ForgotPassword } from "./forgot-password/forgot-password";
export { default as MultiplayerHome } from "./multiplayer-home/multiplayer-home";
export { default as MultiplayerGame } from "./multiplayer-game/multiplayer-game";
